# Generated by Django 2.1.3 on 2018-11-22 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instapic', '0003_auto_20181122_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sign_up_date',
        ),
    ]
