# Generated by Django 2.1.3 on 2018-11-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instapic', '0005_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postid', models.IntegerField()),
                ('liker', models.CharField(max_length=20)),
            ],
        ),
    ]
